//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derminator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_RECIBOS
    {
        public string CIA_Codigo { get; set; }
        public double CXC_Recibo { get; set; }
        public string CXC_Tipo { get; set; }
        public string TAS_Codigo { get; set; }
        public System.DateTime CXC_Fecha { get; set; }
        public string CXC_Cheque { get; set; }
        public string CLI_Cliente { get; set; }
        public double CXC_DescuentoColones { get; set; }
        public double CXC_DescuentoDolares { get; set; }
        public double CXC_MontoColones { get; set; }
        public double CXC_MontoDolares { get; set; }
        public string CXC_Estado { get; set; }
        public string CXC_Observaciones { get; set; }
        public string VEN_Vendedor { get; set; }
        public double VEN_Comision { get; set; }
        public double CXC_TipoCambio { get; set; }
        public string CXC_Moneda { get; set; }
        public short CXC_Contabilizado { get; set; }
        public short CXC_CierreFiscal { get; set; }
        public short CXC_Pendiente { get; set; }
        public double CXC_SaldoColones { get; set; }
        public double CXC_SaldoDolares { get; set; }
        public decimal CXC_Devolucion { get; set; }
        public double TRA_Numero { get; set; }
        public byte[] timestamp { get; set; }
        public string USR_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> USR_Fecha_Modificacion { get; set; }
        public string USR_Usuario_Inclusion { get; set; }
        public Nullable<System.DateTime> USR_Fecha_Inclusion { get; set; }
        public string BNC_Banco { get; set; }
        public string MOV_Tipo { get; set; }
        public Nullable<double> Mov_Numero { get; set; }
        public short CXC_FuePendiente { get; set; }
        public string CXC_Tipo_Dos { get; set; }
        public Nullable<bool> MigradaSAP { get; set; }
    }
}
