//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derminator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_LoadInvoiceMaster
    {
        public double DocNum { get; set; }
        public string CardCode { get; set; }
        public string DocCurrency { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime TaxDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public double NumAtCard { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string ManualNumber { get; set; }
        public string Comments { get; set; }
        public decimal DiscountPercent { get; set; }
        public Nullable<short> SalesPersonCode { get; set; }
        public string U_SCG_TipoDocumento { get; set; }
        public string Project { get; set; }
    }
}
