//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derminator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_CreditNoteDetail
    {
        public double RecordKey { get; set; }
        public string AccountCode { get; set; }
        public string ItemDescription { get; set; }
        public string Currency { get; set; }
        public Nullable<double> LineTotal { get; set; }
        public string TaxCode { get; set; }
        public int DiscountPercent { get; set; }
    }
}
