//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PandoraEntities : DbContext
    {
        public PandoraEntities()
            : base("name=PandoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int GetProjectGeneralStatus(Nullable<int> projectQuoteId)
        {
            var projectQuoteIdParameter = projectQuoteId.HasValue ?
                new ObjectParameter("ProjectQuoteId", projectQuoteId) :
                new ObjectParameter("ProjectQuoteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProjectGeneralStatus", projectQuoteIdParameter);
        }
    
        public virtual ObjectResult<GetSalesByEmployeeByDivision_Result> GetSalesByEmployeeByDivision(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesByEmployeeByDivision_Result>("GetSalesByEmployeeByDivision", startDateParameter, endDateParameter);
        }
    }
}
